### ISSUE TITLE
เวลาจะส่งงานต้องทำอย่างไรครับ

### ISSUE THREAD

**Issue by sornvisit-jeans** [NextGen-AI-Camp/curriculum#2]
ต้องส่ง exercise มั้ยครับ ถ้าต้องส่ง ต้องส่งยังไงครับ

**Comment by nupassion201035** [comment]
เดียวแจ้งให้ทราบอีกทีนะครับ(Discord) สามารถ ทำแล้วเก็บก่อนไว้ได้ครับ
